### ISSUE TITLE
Possible bug in connection release

### ISSUE THREAD

**Issue by tikonen** [3rd-Eden/jackpot#2]
Hi, I'm not sure if this is a bug or I just don't understand the code. The Manager.release splices connection from pool using object as argument instead of its index.

```
// remove it from the pool
this.pool.splice(net, 1);
```

Shouldn't this be actually?

```
// remove it from the pool
this.pool.splice(index, 1);
```

**Comment by 3rd-Eden** [comment]
I cant believe that I missed that!!

I'll test, confirm and update the suite asap. This could be causing the leak =/

**Comment by tikonen** [comment]
Great, I'll wait for update before investigating leak more. It's hard to tell what problems this might have caused as calling splice with object has undefined results.

**Comment by 3rd-Eden** [comment]
@tikonen The slicing might have gone wrong.. but the connection should still be closed because:

https://github.com/3rd-Eden/jackpot/blob/master/lib/jackpot.js#L279-L281

Calls the `destroySoon` or `destroy` method on the net connection it wants to release

**Comment by 3rd-Eden** [comment]
But then again, because the `array#splice` is wrong.. It removes the first item from the pool, instead of the given connection. So when we want to `release` the first connection of the pool, it will not be found and not destroyed..

Anyways, I'm working on extending the tests atm, to see if I can this theory reproduced in a failing test case and then fix it.

Even if it does not resolve my theory, i'll release an updated version of the module and of node-memcached today. I'll give you an heads up of when I have pushed out a new version.
